version: '3'
services:
  web:
    build:
        context: .
    ports:
      - 8000:8000
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
    working_dir: /src
